version: '3'

services:

  kavu-database:
    image: postgres:11.1
    container_name: kavu-database
    environment:
      - POSTGRES_PASSWORD=dbp4ss
      - POSTGRES_DB=kavu
      - POSTGRES_USER=dbuser
    ports:
      - "5432:5432"
    networks:
      - kavu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  kavu-backend:
    image: slonepi/kavu-dechet-backend:0.0.0
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    container_name: kavu-backend
    depends_on:
      - kavu-database
    ports:
      - 5000:5000
    volumes:
      - ./images:/tmp/images
      - ./python-backend:/api
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - kavu-network
    command: python3 dechetAPI.py

networks:
  kavu-network:
    driver: bridge
