version: '3'

services:

  kavu-backend:
    image: slonepi/kavu-dechet-backend:0.0.0
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    container_name: kavu-backend
    depends_on:
      kavu-database:
        condition: service_healthy
    ports:
      - 5000:5000
    links:
      - kavu-database
    volumes:
      - ./images:/tmp/images
      - ./python-backend:/api
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 dechetAPI.py

  kavu-database:
    image: postgres:11.1
    container_name: kavu-database
    environment:
      - POSTGRES_PASSWORD=dbp4ss
      - POSTGRES_DB=kavu
      - POSTGRES_USER=dbuser
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  database:
