version: '3'

services: 

#  rc-database:
#    image: postgres:11.1
#    container_name: rc-database
#    environment:
#      - POSTGRES_PASSWORD=dbp4ss
#      - POSTGRES_DB=reference_collector
#      - POSTGRES_USER=dbuser
#    ports:
#      - "5432:5432"
#    networks:
#      - rc

  kavu-dechet-back:
    image: slonepi/kavu-dechet-backend:0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-kavu
    ports:
      - 8080:8080
    volumes:
      - "./images:/tmp/images"
#    networks:
#      - keycloak
#      - rc

#networks:
#  keycloak:
#    name: keycloak-network
#    external: true
#  rc:
#    name: rc
#    driver: bridge